version: '3.3'
services:
  php-apache-environment:
    container_name: ora
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        - db-ora
    volumes:
    - ./:/var/www/html/
    ports:
      - 8070:80
    expose:
      - 80
  db-ora:
    container_name: db-ora
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ora@#admin123
        MYSQL_DATABASE: ora
        MYSQL_USER: ora#user
        MYSQL_PASSWORD: ora@#123
    ports:
      - "9910:3306"
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - 3306
volumes:
  mysql:
    driver: local
